# Generated by Django 5.2.1 on 2025-05-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeproposal',
            name='comment',
            field=models.TextField(verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='exchangeproposal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='exchangeproposal',
            name='status',
            field=models.CharField(choices=[('pending', 'На рассмотрении'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('books', 'Книги'), ('electronics', 'Электроника'), ('cloth', 'Одежда'), ('furniture', 'Мебель'), ('other', 'Другое')], max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.CharField(choices=[('new', 'Новое'), ('like new', 'Как новое'), ('used', 'Б/У'), ('for parts', 'На запчасти')], max_length=50, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
