# Generated by Django 5.2.1 on 2025-05-17 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_exchangeproposal_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangeproposal',
            options={'ordering': ['-created_at'], 'verbose_name': 'Предложение обмена', 'verbose_name_plural': 'Предложения обмена'},
        ),
    ]
